export {TextDisplay} from './text-display.tsx'
export {TextInput} from './text-input.tsx'
export {Statistics} from './statistic.tsx'
export {ResultScreen} from './result-screen.tsx'
export {ChooseTextType} from './choose-text-type.tsx'
export {Header} from './header.tsx'
export {Container} from './container.tsx'